{
  "formatVersion": "1.1",
  "component": {
    "group": "com.genexus.android",
    "module": "FlexibleClient",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.genexus",
          "module": "gxandroid",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "stax",
              "module": "stax-api"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-jdk18on"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcprov-jdk18on"
            },
            {
              "group": "xpp3",
              "module": "*"
            },
            {
              "group": "org.apache.santuario",
              "module": "xmlsec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "FlexibleClient-1.8.0.aar",
          "url": "FlexibleClient-1.8.0.aar",
          "size": 2526837,
          "sha512": "10c3b2d849917293b39b35a09ee1ba89138a03f3bdbd3089cf40cf257e986a3217aad060c5d0d8966ff4fb83b20e131dc192941f643f02aa43ab1a2f27c5cc31",
          "sha256": "1c1dd087c53775e2e4dcab65d63c824fb3e2d28d064afd7c07b80d38e3515950",
          "sha1": "c7a04a142eed6aa9ebd1ef7599b3c25bd5c181a9",
          "md5": "6ad5809bff001e2f94995768d72ef90c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.genexus",
          "module": "gxandroid",
          "version": {
            "requires": "4.1.1"
          },
          "excludes": [
            {
              "group": "stax",
              "module": "stax-api"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcpkix-jdk18on"
            },
            {
              "group": "org.bouncycastle",
              "module": "bcprov-jdk18on"
            },
            {
              "group": "xpp3",
              "module": "*"
            },
            {
              "group": "org.apache.santuario",
              "module": "xmlsec"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.browser",
          "module": "browser",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "19.2.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "17.4.0"
          }
        },
        {
          "group": "org.simpleframework",
          "module": "simple-xml",
          "version": {
            "requires": "2.7.1"
          },
          "excludes": [
            {
              "group": "stax",
              "module": "*"
            },
            {
              "group": "xpp3",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "com.genexus.android",
          "module": "roundedimageview",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "me.leolin",
          "module": "ShortcutBadger",
          "version": {
            "requires": "1.1.22"
          }
        },
        {
          "group": "com.caverock",
          "module": "androidsvg-aar",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp-urlconnection",
          "version": {
            "requires": "4.8.0"
          }
        },
        {
          "group": "com.pierfrancescosoffritti.androidyoutubeplayer",
          "module": "core",
          "version": {
            "requires": "12.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "FlexibleClient-1.8.0.aar",
          "url": "FlexibleClient-1.8.0.aar",
          "size": 2526837,
          "sha512": "10c3b2d849917293b39b35a09ee1ba89138a03f3bdbd3089cf40cf257e986a3217aad060c5d0d8966ff4fb83b20e131dc192941f643f02aa43ab1a2f27c5cc31",
          "sha256": "1c1dd087c53775e2e4dcab65d63c824fb3e2d28d064afd7c07b80d38e3515950",
          "sha1": "c7a04a142eed6aa9ebd1ef7599b3c25bd5c181a9",
          "md5": "6ad5809bff001e2f94995768d72ef90c"
        }
      ]
    }
  ]
}
